version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: civicbalance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/civicbalance
    command: bash -lc "uvicorn src.api:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
volumes:
  pgdata: